export type PrivateCandidateMapFacility = {
  id: string;
  name: string;
  department: string;
  locality: string;
  address: string;
  places: null;
  lat: number;
  lng: number;
  precision: "referencial";
  precisionLabel: string;
  statusGroup: "candidate_private";
  statusStage: string;
  statusShort: string;
  sourceLabel: string;
  mspFinal: false;
  mspRegistroHistorico: false;
  midesSocial: false;
  pacp: false;
  otherSource: false;
  pendingVerification: false;
  appDiscovered: false;
  privateCandidate: true;
  privateCandidateEvidenceTier: "A" | "B" | "C";
  privateCandidateSourceUrl?: string;
  privateCandidateRetrievedAt?: string;
};

export function mapPrivateCandidateToFacility(value: unknown): PrivateCandidateMapFacility | null;
export function mapPrivateCandidatesToFacilities(values: unknown): PrivateCandidateMapFacility[];
