from enum import StrEnum


class Classification(StrEnum):
    MATCHED_HABILITATED = "MATCHED_HABILITATED"
    MATCHED_IN_PROCESS = "MATCHED_IN_PROCESS"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    NOT_MATCHED = "NOT_MATCHED"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"


class OfficialStatus(StrEnum):
    HABILITATED = "HABILITATED"
    IN_PROCESS = "IN_PROCESS"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class ReviewState(StrEnum):
    PENDING = "PENDING"
    IN_REVIEW = "IN_REVIEW"
    COMPLETED = "COMPLETED"


class EvidenceLevel(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    UNASSESSED = "UNASSESSED"


class SourceType(StrEnum):
    BRAVE_SEARCH = "BRAVE_SEARCH"
    GOOGLE_PLACE_LINK = "GOOGLE_PLACE_LINK"
    MANUAL = "MANUAL"


class ImportFormat(StrEnum):
    CSV = "CSV"
    JSON = "JSON"
    XLSX = "XLSX"
    PDF_DERIVED_CSV = "PDF_DERIVED_CSV"
    PDF_DERIVED_JSON = "PDF_DERIVED_JSON"
